chain_split_single_child = true
combine_control_expr = false
condense_wildcard_suffixes = true
control_style = "Legacy"
fn_brace_style = "AlwaysNextLine"
fn_return_indent = "WithWhereClause"
fn_single_line = true
format_strings = true
generics_indent = "Visual"
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
match_pattern_separator_break_point = "Front"
max_width = 80
multiline_closure_forces_block = true
multiline_match_arm_forces_block = true
normalize_comments = true
reorder_imports_in_group = true
reorder_imported_names = true
struct_field_align_threshold = 8
spaces_around_ranges = true
struct_variant_width = 0
use_try_shorthand = true
wrap_comments = true
fn_call_style = "Block"
write_mode = "overwrite"
