#ifndef CONF_CLOCK_H
#define CONF_CLOCK_H

// Used by FreeRTOS, should match the final clock rate when FreeRTOS is up
// and running
#define BOARD_MCK 12000000u

#define CONFIG_SYSCLK_SOURCE        SYSCLK_SRC_MAINCK_12M_RC
#define CONFIG_SYSCLK_PRES          SYSCLK_PRES_1
#define BOARD_FREQ_SLCK_XTAL    12000000U
#define BOARD_FREQ_SLCK_BYPASS  12000000U
#define BOARD_FREQ_MAINCK_XTAL  12000000U
#define BOARD_FREQ_MAINCK_BYPASS 12000000U
#define BOARD_OSC_STARTUP_US    (15625UL)

// SAM4S XPLAINED
/*
#define CONFIG_SYSCLK_SOURCE        SYSCLK_SRC_PLLACK
#define CONFIG_SYSCLK_PRES          SYSCLK_PRES_2
#define CONFIG_PLL0_SOURCE          PLL_SRC_MAINCK_XTAL
#define CONFIG_PLL0_MUL             20
#define CONFIG_PLL0_DIV             1
#define CONFIG_PLL1_SOURCE          PLL_SRC_MAINCK_XTAL
#define CONFIG_PLL1_MUL             16
#define CONFIG_PLL1_DIV             2
#define BOARD_FREQ_MAINCK_XTAL      12000000U
#define BOARD_FREQ_MAINCK_BYPASS    12000000U
#define BOARD_FREQ_SLCK_XTAL        32768U
#define BOARD_FREQ_SLCK_BYPASS      32768U
#define BOARD_OSC_STARTUP_US        15625
*/

#endif // CONF_CLOCK_H
