#ifndef CONF_CLOCK_H
#define CONF_CLOCK_H

//#define CONFIG_SYSCLK_SOURCE        SYSCLK_SRC_MAINCK_12M_RC
#define CONFIG_SYSCLK_SOURCE        SYSCLK_SRC_SLCK_RC
#define CONFIG_SYSCLK_PRES          SYSCLK_PRES_1

#endif // CONF_CLOCK_H
