#ifndef CONF_USART_H
#define CONF_USART_H

#define USART_SERIAL            USART1
#define USART_SERIAL_ID         ID_USART1
#define USART_SERIAL_IRQ        USART1_IRQn
#define USART_SERIAL_BAUDRATE   115200
#define USART_SERIAL_CHAR_LENGTH     US_MR_CHRL_8_BIT
#define USART_SERIAL_PARITY          US_MR_PAR_NO
#define USART_SERIAL_STOP_BIT        US_MR_NBSTOP_1_BIT

#endif // CONF_USART_H
