#ifndef CONF_CLOCK_H
#define CONF_CLOCK_H

#define BOARD_MCK (120u*1000000u)

#define CONFIG_SYSCLK_SOURCE        SYSCLK_SRC_PLLACK
#define CONFIG_SYSCLK_PRES          SYSCLK_PRES_2
#define CONFIG_PLL0_SOURCE          PLL_SRC_MAINCK_12M_RC
#define CONFIG_PLL0_MUL             20
#define CONFIG_PLL0_DIV             1
#define CONFIG_PLL1_SOURCE          PLL_SRC_MAINCK_12M_RC
#define CONFIG_PLL1_MUL             20
#define CONFIG_PLL1_DIV             1

#define BOARD_FREQ_MAINCK_XTAL      (12u*1000000u)
#define BOARD_FREQ_MAINCK_BYPASS    (12u*1000000u)
#define BOARD_FREQ_SLCK_XTAL        32768u
#define BOARD_FREQ_SLCK_BYPASS      32768u
#define BOARD_OSC_STARTUP_US        15625

#if 0
#define CONFIG_SYSCLK_SOURCE        SYSCLK_SRC_MAINCK_12M_RC
#define CONFIG_SYSCLK_PRES          SYSCLK_PRES_1
#define BOARD_FREQ_SLCK_XTAL    (12u*1000000u)
#define BOARD_FREQ_SLCK_BYPASS  (12u*1000000u)
#define BOARD_FREQ_MAINCK_XTAL  (12u*1000000u)
#define BOARD_FREQ_MAINCK_BYPASS (12u*1000000u)
#define BOARD_OSC_STARTUP_US    (15625UL)
#endif


#endif // CONF_CLOCK_H
